export const TOGGLE_MOBILE_START_MENU_VISIBILITY: string =
  'TOGGLE_MOBILE_START_MENU_VISIBILITY';
export const TOGGLE_EDIT_PROFILE_VISIBILITY: string =
  'TOGGLE_EDIT_PROFILE_VISIBILITY';
export const CHANGE_MOBILE_HOME_CATEGORY: string =
  'CHANGE_MOBILE_HOME_CATEGORY';
